//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public int AuthorID { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Story { get; set; }
        public string ShortName { get; set; }
    }
}
