//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<int> PubComID { get; set; }
        public string Decription { get; set; }
        public string CoverPicture { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool OutOfStock { get; set; }
        public string ShortName { get; set; }
    }
}
